using System.Text.Json;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace LastOneRich.Core;

/// <summary>
/// Bitmap font rendered through SpriteBatch (GDD 12: "UI is drawn with SpriteBatch + bitmap font").
/// Atlas + metrics generated by tools/make_font.py — no Content Pipeline required.
/// </summary>
public sealed class BitmapFont
{
    public sealed class Glyph
    {
        public int X { get; set; }
        public int Y { get; set; }
        public int W { get; set; }
        public int H { get; set; }
        public float Adv { get; set; }
        public int Ox { get; set; }
        public int Oy { get; set; }
    }

    readonly Texture2D _tex;
    readonly Dictionary<string, Glyph> _map = new();
    public int LineHeight { get; private set; }
    public int BaseSize { get; private set; }

    public BitmapFont(GraphicsDevice gd, string pngPath, string jsonPath)
    {
        _tex = Texture2D.FromStream(gd, File.OpenRead(pngPath));
        var meta = JsonSerializer.Deserialize<FontMeta>(File.ReadAllText(jsonPath), Json.Options);
        LineHeight = meta.LineHeight;
        BaseSize = meta.Size;
        foreach (var kv in meta.Chars) _map[kv.Key] = kv.Value;
    }

    public sealed class FontMeta
    {
        public int TexW { get; set; }
        public int TexH { get; set; }
        public int Size { get; set; }
        public int LineHeight { get; set; }
        public Dictionary<string, Glyph> Chars { get; set; } = new();
    }

    public Vector2 Measure(string text, float scale = 1f)
    {
        float x = 0;
        foreach (var ch in text)
        {
            if (_map.TryGetValue(ch.ToString(), out var g)) x += g.Adv * scale;
            else x += BaseSize * 0.3f * scale;
        }
        return new Vector2(x, LineHeight * scale);
    }

    /// <summary>Draw text. pos is the layout position; origin shifts it (e.g. 0.5 centers horizontally).</summary>
    public void Draw(SpriteBatch sb, string text, Vector2 pos, Color color, float scale = 1f,
                     float rotRad = 0f, Vector2? origin = null, bool shadow = false, Color? shadowColor = null)
    {
        var org = origin ?? Vector2.Zero;

        if (shadow)
        {
            var sc = shadowColor ?? new Color(0, 0, 0, 200);
            Emit(sb, text, pos + new Vector2(2f, 3f) * scale, sc, scale, rotRad, org);
        }
        Emit(sb, text, pos, color, scale, rotRad, org);
    }

    void Emit(SpriteBatch sb, string text, Vector2 pos, Color color, float scale, float rotRad, Vector2 origin)
    {
        float cursor = 0;
        foreach (var ch in text)
        {
            if (!_map.TryGetValue(ch.ToString(), out var g)) { cursor += BaseSize * 0.3f; continue; }
            if (g.W > 0 && g.H > 0)
            {
                // origin is in SCREEN pixels (like SpriteBatch): screen = pos + glyph*scale - origin
                if (rotRad == 0f)
                {
                    int dx = (int)MathF.Round(pos.X + (cursor + g.Ox) * scale - origin.X);
                    int dy = (int)MathF.Round(pos.Y + g.Oy * scale - origin.Y);
                    int dw = (int)MathF.Round(g.W * scale);
                    int dh = (int)MathF.Round(g.H * scale);
                    sb.Draw(_tex, new Rectangle(dx, dy, dw, dh), new Rectangle(g.X, g.Y, g.W, g.H), color);
                }
                else
                {
                    var screen = new Vector2(pos.X + (cursor + g.Ox) * scale - origin.X,
                                             pos.Y + g.Oy * scale - origin.Y);
                    float cs = MathF.Cos(rotRad), sn = MathF.Sin(rotRad);
                    var rel = screen - pos;
                    var dest = pos + new Vector2(rel.X * cs - rel.Y * sn, rel.X * sn + rel.Y * cs);
                    sb.Draw(_tex, dest, new Rectangle(g.X, g.Y, g.W, g.H), color, rotRad, Vector2.Zero, scale, SpriteEffects.None, 0f);
                }
            }
            cursor += g.Adv;
        }
    }

    public void DrawOutlined(SpriteBatch sb, string text, Vector2 pos, Color color, float scale = 1f,
                             float rotRad = 0f, Vector2? origin = null)
    {
        var off = new Vector2(2.2f, 2.6f) * scale;
        var black = new Color(8, 8, 14, 235);
        Draw(sb, text, pos + new Vector2(off.X, 0), black, scale, rotRad, origin);
        Draw(sb, text, pos + new Vector2(-off.X, 0), black, scale, rotRad, origin);
        Draw(sb, text, pos + new Vector2(0, off.Y), black, scale, rotRad, origin);
        Draw(sb, text, pos + new Vector2(0, -off.Y), black, scale, rotRad, origin);
        Draw(sb, text, pos, color, scale, rotRad, origin);
    }
}
